global:
  scrape_interval: 15s   # Frequência das coletas

scrape_configs:
  - job_name: "flask-api"
    metrics_path: "/metrics"     # Endpoint automático criado pelo PrometheusMetrics
    static_configs:
      - targets: ["web:5000"]